/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class EditListPlan extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pstm = null;
    private String listPlanName;
    private String listDescription;
    private int set;
    private int reps;
    private int planId;
    private int listID;
    private String nameDay;

    private EditListPlan() {
        initComponents();
        setTitle("Edit");
        setResizable(false);
    }

    public EditListPlan(int planId) {
        this.planId = planId;
        try {
            initComponents();
            setTitle("Edit");
            setResizable(false);
            conn = MySQLConnect.getMySQLConnection();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EditListPlan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EditListPlan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    EditListPlan(int planId, String listPlanName, String listDescription, int reps, int set, int listID) throws ClassNotFoundException, SQLException {
        this.planId = planId;
        this.listPlanName = listPlanName;
        this.listDescription = listDescription;
        this.reps = reps;
        this.set = set;
        this.listID = listID;
        //this.nameDay = nameDay;
        try {
           // tt();
            initComponents();
            conn = MySQLConnect.getMySQLConnection();
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
        } catch (SQLException ex) {
            System.out.println(ex);
        } catch (NullPointerException ex) {
            System.out.println(ex.getMessage());
        }
        txtLName.setText(listPlanName);
        txtDes.setText(listDescription);
        txtReps.setText(reps + "");
        txtSet.setText(set + "");
       
        //boxChooseDay

    }

    public String getListDescription() {
        return listDescription;
    }

    public void setListDescription(String listDescription) {
        this.listDescription = listDescription;
    }

    public String getListPlanName() {
        return listPlanName;
    }

    public void setListPlanName(String listPlanName) {
        this.listPlanName = listPlanName;
    }

    public int getSet() {
        return set;
    }

    public void setSet(int set) {
        this.set = set;
    }

    public int getReps() {
        return reps;
    }

    public void setReps(int reps) {
        this.reps = reps;
    }

    public int getPlanId() {
        return planId;
    }

    public void setPlanId(int planId) {
        this.planId = planId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSet = new javax.swing.JLabel();
        txtDes = new javax.swing.JTextField();
        txtReps = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSet = new javax.swing.JTextField();
        lblLName = new javax.swing.JLabel();
        lblDes = new javax.swing.JLabel();
        lblReps = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        photolbl = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        lblcancel = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        lblsave = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblSet.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblSet.setForeground(new java.awt.Color(255, 255, 255));
        lblSet.setText("Set");

        txtDes.setMinimumSize(new java.awt.Dimension(59, 20));
        txtDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesActionPerformed(evt);
            }
        });

        txtReps.setMinimumSize(new java.awt.Dimension(59, 20));
        txtReps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRepsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Edit List Plan");

        txtSet.setMinimumSize(new java.awt.Dimension(59, 20));
        txtSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSetActionPerformed(evt);
            }
        });

        lblLName.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblLName.setForeground(new java.awt.Color(255, 255, 255));
        lblLName.setText("List name");

        lblDes.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblDes.setForeground(new java.awt.Color(255, 255, 255));
        lblDes.setText("Description");

        lblReps.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblReps.setForeground(new java.awt.Color(255, 255, 255));
        lblReps.setText("Reps");

        txtLName.setMinimumSize(new java.awt.Dimension(59, 20));
        txtLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLNameActionPerformed(evt);
            }
        });

        photolbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Santex/image/edit5.png"))); // NOI18N

        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Santex/image/file (4).png"))); // NOI18N
        cancelBtn.setContentAreaFilled(false);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        lblcancel.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lblcancel.setForeground(new java.awt.Color(255, 255, 255));
        lblcancel.setText("CANCEL ");
        lblcancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcancelMouseClicked(evt);
            }
        });

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Santex/image/diskette.png"))); // NOI18N
        saveBtn.setContentAreaFilled(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        lblsave.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lblsave.setForeground(new java.awt.Color(255, 255, 255));
        lblsave.setText("SAVE");
        lblsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(photolbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblsave)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcancel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGap(115, 115, 115))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblLName)
                        .addComponent(lblDes))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSet)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblReps)
                        .addGap(60, 60, 60)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDes, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSet, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReps, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(256, 256, 256))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(photolbl))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(txtDes, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(txtReps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(txtSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLName)
                        .addGap(44, 44, 44)
                        .addComponent(lblDes)
                        .addGap(127, 127, 127)
                        .addComponent(lblReps)
                        .addGap(52, 52, 52)
                        .addComponent(lblSet)))
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblsave, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLNameActionPerformed
        setResizable(false);
    }//GEN-LAST:event_txtLNameActionPerformed

    private void txtSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSetActionPerformed
        setResizable(false);
    }//GEN-LAST:event_txtSetActionPerformed

    private void txtRepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRepsActionPerformed
        setResizable(false);
    }//GEN-LAST:event_txtRepsActionPerformed

    private void txtDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesActionPerformed
        setResizable(false);
    }//GEN-LAST:event_txtDesActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
          System.out.println("listID" + listID);
        try {
            String sql = "update LIST set ListName = ? , descriptionList = ? , reps = ? , `set` = ? where listID=" + listID;
            pstm = (PreparedStatement) conn.prepareStatement(sql);
            pstm.setString(1, txtLName.getText());
            pstm.setString(2, txtDes.getText());
            pstm.setString(3, txtReps.getText());
            pstm.setString(4, txtSet.getText());
            pstm.executeUpdate();
            JOptionPane.showMessageDialog(null, "Edit successfully");
            DetailList1 dl = new DetailList1(planId);
            dl.setVisible(true);
            dl.setLocationRelativeTo(null);
            dl.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.setVisible(false);

        } catch (SQLException ex) {
            Logger.getLogger(CreatePlan1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        DetailList1 dl = new DetailList1(planId);
        dl.setVisible(true);
        dl.setLocationRelativeTo(null);
        dl.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void lblcancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcancelMouseClicked
        DetailList1 dl = new DetailList1(planId);
        dl.setVisible(true);
        dl.setLocationRelativeTo(null);
        dl.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_lblcancelMouseClicked

    private void lblsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsaveMouseClicked
         System.out.println("listID" + listID);
        try {
            String sql = "update LIST set ListName = ? , descriptionList = ? , reps = ? , `set` = ? where listID=" + listID;
            pstm = (PreparedStatement) conn.prepareStatement(sql);
            pstm.setString(1, txtLName.getText());
            pstm.setString(2, txtDes.getText());
            pstm.setString(3, txtReps.getText());
            pstm.setString(4, txtSet.getText());
            pstm.executeUpdate();
            JOptionPane.showMessageDialog(null, "Edit successfully");
            DetailList1 dl = new DetailList1(planId);
            dl.setVisible(true);
            dl.setLocationRelativeTo(null);
            dl.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.setVisible(false);

        } catch (SQLException ex) {
            Logger.getLogger(CreatePlan1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblsaveMouseClicked

//    public void tt() throws ClassNotFoundException, SQLException {
//        Connection conn = MySQLConnect.getMySQLConnection();
//        System.out.println("selecting..");
//        PreparedStatement pstm = conn.prepareStatement("SELECT nameDay,dayperweek from PLAN where planID = " + planId);
//        ResultSet rs = pstm.executeQuery();
//        while (rs.next()) {
//            String days = rs.getString("nameDay");
//            System.out.println("" + rs.getString("nameDay"));
//            System.out.println("" + rs.getInt("dayperweek"));
//            int start = 0;
//            for (int i = 1; i <= rs.getInt("dayperweek"); i++) {
//                String eachDay = days.substring(start, days.indexOf(" ", start));
//                start = days.indexOf(" ", start) + 1;
                //boxChooseDay.addItem(eachDay);

//            }
 //       }
    //}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditListPlan().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDes;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblReps;
    private javax.swing.JLabel lblSet;
    private javax.swing.JLabel lblcancel;
    private javax.swing.JLabel lblsave;
    private javax.swing.JLabel photolbl;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField txtDes;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtReps;
    private javax.swing.JTextField txtSet;
    // End of variables declaration//GEN-END:variables

}
